var words = [
    {word: "Un appartement", translation: "Een appartement"},
    {word: "Une maison", translation: "Een huis"},
    {word: "Une chambre", translation: "Een kamer"},
    {word: "Une cuisine", translation: "Een keuken"},
    {word: "Un garage", translation: "Een garage"},
    {word: "Un jardin", translation: "Een tuin"},
    {word: "Une salle de séjour", translation: "Een woonkamer"},
    {word: "Une salle de bains", translation: "Een badkamer"},
    {word: "Les toilettes", translation: "Het toilet"},
    {word: "Un étage", translation: "Een verdiep"},
    {word: "Une armoire", translation: "Een kast"},
    {word: "Un placard", translation: "Een inbouwkast"},
    {word: "Un bureau", translation: "Een bureau"},
    {word: "Une table", translation: "Een tafel"},
    {word: "Un lit", translation: "Een bed"},
    {word: "Une chaise", translation: "Een stoel"},
    {word: "Une lampe", translation: "Een lamp"},
    {word: "Une douche", translation: "Een douche"},
    {word: "Une porte", translation: "Een deur"},
    {word: "Une fenêtre", translation: "Een venster"},
    {word: "Un fauteuil", translation: "Een zetel"},
    {word: "Un voisin", translation: "Een buurman"},
    {word: "Une voisine", translation: "Een buurvrouw"},
    {word: "Au premier étage", translation: "Op de eerste verdieping"},
    {word: "Où sont les toilettes, s.v.p.?", translation: "Waar is het toilet aub?"},
    {word: "Des loisirs", translation: "Vrijetijdsbesteding"},
    {word: "Un jeu", translation: "Een spel"},
    {word: "Un ordinateur", translation: "Een computer"},
    {word: "L’internet", translation: "Het internet"},
    {word: "Un courriel", translation: "Een e-mail"},
    {word: "Une balle", translation: "Een (kleine) bal"},
    {word: "Un ballon", translation: "Een (grote) bal, een ballon"},
    {word: "Le cinéma", translation: "De bioscoop"},
    {word: "Un film", translation: "Een film"},
    {word: "Une télévision", translation: "Een televisie"},
    {word: "Une radio", translation: "Een radio"},
    {word: "Un CD", translation: "Een cd"},
    {word: "Un DVD", translation: "Een dvd"},
    {word: "Un voyage", translation: "Een reis"},
    {word: "Une valise", translation: "Een valies"},
    {word: "Les vacances", translation: "De vakantie"},
    {word: "Une promenade", translation: "Een wandeling"},
    {word: "Un match", translation: "Een wedstrijd"},
    {word: "Un sport", translation: "Een sport"},
    {word: "Le football", translation: "Voetbal"},
    {word: "Le tennis", translation: "Tennis"},
    {word: "Le basket", translation: "Basketbal"},
    {word: "La gymnastique", translation: "Het turnen"},
    {word: "Le vélo", translation: "Het fietsen"},
    {word: "La musique", translation: "Muziek"},
    {word: "Une chanson", translation: "Een liedje"},
    {word: "Surfer sur l’internet", translation: "Surfen op het internet"},
    {word: "J’aime", translation: "Ik hou van"},
    {word: "Je n’aime pas", translation: "Ik hou er niet van"},
    {word: "J’adore", translation: "Ik ben er dol op"},
    {word: "J’ai gagné", translation: "Ik heb gewonnen"},
    {word: "Faire du sport", translation: "Sport beoefenen"},
    {word: "Jouer", translation: "Spelen"},
    {word: "Se promener", translation: "Wandelen"},
    {word: "Nager", translation: "Zwemmen"},
    {word: "Danser", translation: "Dansen"},
    {word: "Tchatter", translation: "Chatten"},
    {word: "Surfer", translation: "Surfen"},
    {word: "Télécharger", translation: "Opladen"},
    {word: "Je fais du basket", translation: "Ik doe aan basket"},
    {word: "Je fais de la musique", translation: "Ik speel muziek"},
    {word: "Je joue du piano", translation: "Ik speel piano"},
    {word: "Je joue de la guitare", translation: "Ik speel gitaar"},
    {word: "Je joue à la balle", translation: "Ik speel met de bal"},
    {word: "Je joue au foot", translation: "Ik speel voetbal"},
    {word: "Je joue aux cartes", translation: "Ik speel met de kaarten"},
    {word: "Une école", translation: "Een school"},
    {word: "Un directeur", translation: "Een directeur"},
    {word: "Une directrice", translation: "Een directrice"},
    {word: "Un professeur", translation: "Een leraar/lerares"},
    {word: "Un élève", translation: "Een leerling"},
    {word: "Une classe", translation: "Een klas"},
    {word: "Un banc", translation: "Een bank"},
    {word: "Un bureau", translation: "Een bureau"},
    {word: "Un tableau", translation: "Een bord"},
    {word: "Un cahier", translation: "Een schrift"},
    {word: "Une feuille", translation: "Een blad"},
    {word: "Un livre", translation: "Een boek"},
    {word: "Un portable", translation: "Een laptop"},
    {word: "Une photo", translation: "Een foto"},
    {word: "Un stylo", translation: "Een pen"},
    {word: "Un crayon", translation: "Een potlood"},
    {word: "Une gomme", translation: "Een gom"},
    {word: "Un mot", translation: "Een woord"},
    {word: "Une phrase", translation: "Een zin"},
    {word: "Un texte", translation: "Een tekst"},
    {word: "Une page", translation: "Een bladzijde"},
    {word: "Un devoir", translation: "Een huiswerk"},
    {word: "Un exercice", translation: "Een oefening"},
    {word: "Une leçon", translation: "Een les"},
    {word: "Une faute", translation: "Een fout"},
    {word: "Apprendre", translation: "Leren"},
    {word: "Lire", translation: "Lezen"},
    {word: "Écrire", translation: "Schrijven"},
    {word: "Écouter", translation: "Luisteren"},
    {word: "Regarder", translation: "Kijken"},
    {word: "Commencer", translation: "Beginnen"},
    {word: "Travailler", translation: "Werken"},
    {word: "Parler", translation: "Spreken"},
    {word: "Raconter", translation: "Vertellen"},
    {word: "Un avion", translation: "Een vliegtuig"},
    {word: "Un bateau", translation: "Een boot"},
    {word: "Un autobus", translation: "Een bus"},
    {word: "Une moto", translation: "Een motor"},
    {word: "Un métro", translation: "Een metro"},
    {word: "Un train", translation: "Een trein"},
    {word: "Un vélo", translation: "Een fiets"},
    {word: "Une voiture", translation: "Een auto"},
    {word: "Un camion", translation: "Een vrachtwagen"},
    {word: "Un carrefour", translation: "Een kruispunt"},
    {word: "Un rond-point", translation: "Een rotonde"},
    {word: "Un agent de police", translation: "Een politieagent"},
    {word: "Tout droit", translation: "Rechtdoor"},
    {word: "À gauche", translation: "Naar links"},
    {word: "À droite", translation: "Naar rechts"},
    {word: "Les feux", translation: "De verkeerslichten"},
    {word: "Je prends le bus", translation: "Ik neem de bus"},
    {word: "Je vais à pied", translation: "Ik ga te voet"},
    {word: "Je vais en avion", translation: "Ik ga met het vliegtuig"},
    {word: "Je vais en bateau", translation: "Ik ga met de boot"},
    {word: "Je vais en vélo", translation: "Ik ga met de fiets"},
    {word: "C’est en Belgique", translation: "Het ligt in België"},
    {word: "C’est à Paris", translation: "Het ligt in Parijs"},
    {word: "Prenez la première rue à droite", translation: "Neem de eerste straat rechts"},
    {word: "Prenez la deuxième rue à gauche", translation: "Neem de tweede straat links"},
    {word: "Un magasin", translation: "Een winkel"},
    {word: "Un supermarché", translation: "Een supermarkt"},
    {word: "Un prix", translation: "Een prijs"},
    {word: "La caisse", translation: "De kassa"},
    {word: "Un euro", translation: "Een euro"},
    {word: "Un cent", translation: "Een cent"},
    {word: "Un centime", translation: "Een cent"},
    {word: "Un kilo", translation: "Eén kilo"},
    {word: "Une bouteille", translation: "Een fles"},
    {word: "Un cadeau", translation: "Een geschenk"},
    {word: "Ouvert", translation: "Open"},
    {word: "Fermé", translation: "Gesloten"},
    {word: "Acheter", translation: "Kopen"},
    {word: "Vendre", translation: "Verkopen"},
    {word: "Payer", translation: "Betalen"},
    {word: "Je cherche", translation: "Ik zoek"},
    {word: "Où est", translation: "Waar is"},
    {word: "Je voudrais", translation: "Ik zou graag"},
    {word: "Ça fait combien", translation: "Hoeveel kost het"},
    {word: "Ça fait 8 euros", translation: "Het kost 8 euro"},
    {word: "Un kilo de", translation: "Een kilo van"},
    {word: "100 grammes de", translation: "100 gram van"}
];
